//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS_DETAILS
    {
        public int ID { get; set; }
        public Nullable<int> ID_ORDER { get; set; }
        public Nullable<int> ID_PRODUCT { get; set; }
        public Nullable<decimal> UNITS { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public Nullable<System.DateTime> DATE_MODIFI { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
